version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - "8080:80"
  api:
    image: node:latest
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/home/node/app
    command: "npm start"
    ports:
      - "800:7000"