version: '3'
services:
  web:
    container_name: nginxserver
    build:
      dockerfile: Dockerfile1
    ports:
      - "8080:80"
  api:
    container_name: expressserver
    build: 
      dockerfile: Dockerfile2
    ports:
      - "8081:7000"
