version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - "8080:80"
  api:
    container_name: expressserver
    build: 
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/home/node/app
    ports:
      - "8081:7000"